### ISSUE TITLE
Fatal error: Call to undefined function resolve() in vendor/yansongda/laravel-parsehtml/src/helpers.php:15

### ISSUE THREAD

**Issue by ghost** [yansongda/laravel-parsehtml#2]
[2018-01-17 20:24:33] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Fatal error: Call to undefined function resolve() in redacted/vendor/yansongda/laravel-parsehtml/src/helpers.php:15
Stack trace:
#0 redacted.php(89): parsehtml('\n<h2 id="genera...')
#1 [internal function]: App\Console\Commands\ContentPages->handle()
#2 redacted/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#3 redacted/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#4 redacted/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 redacted/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 redacted/vendor/symfony/console/Application.php(791): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 redacted/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\ContentPages), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 redacted/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 redacted/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 redacted/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 {main}

**Comment by ghost** [comment]
This is a 5.2 project. Perhaps you require a more recent "laravel/framework" than "5.2.*"?

**Comment by ghost** [comment]
Appears to be introduced in 5.3.

**Comment by yansongda** [comment]
Thx for your using!

I'll repair this by using `app()` function to be compatible with 5.1.

**Comment by yansongda** [comment]
This issue is fixed.You can `composer update` to update to v1.0.3. 

Thx for your using again!
