### ISSUE TITLE
Namespace

### ISSUE THREAD

**Issue by przemyslaw-lapinski** [yansongda/laravel-parsehtml#4]
There is a namespace error in Readme.md. 

https://github.com/yansongda/laravel-parsehtml/blob/master/src/ParsehtmlServiceProvider.php#L3

and in Readme:
Yansongda\LaravelParsedown\ParsehtmlServiceProvider::class,

same for Facade

**Comment by yansongda** [comment]
Fixed.

Thx for your support.
